---
controllers: 3
compute_nodes: 2

# Set a default name for the openstack user
os_username: dhc

controller_name: "{{os_username}}-kolla-controller%02d"
compute_node_name: "{{os_username}}-kolla-compute%02d"
operator_name: "{{os_username}}-kolla-operator"
vip_name: "{{os_username}}-kolla-vip"
internal_network_name: "{{os_username}}-kolla-internal-network"
external_network_name: "{{os_username}}-kolla-neutron-external-network"
router_name: "{{os_username}}-kolla-router"

secgroups:
  - default

image: Ubuntu-16.04
flavor: gp1.warpspeed
key_name: prod_iad2
key: ~/.ssh/{{key_name}}.pem 
public_network: public
ansible_user: ubuntu

# The network to which the build nodes should be connected.
# It will be created
internal_network_cidr: 172.17.100.0/24
external_network_cidr: 172.17.200.0/24

# Kolla branch
kolla_version: stable/newton
# VIP used by HAProxy, this has to be a unused ip on the internal_network
internal_vip_address: "172.17.100.254"
